"""
Django settings for A project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xi$1w*ofv^0ko+5@pw)3jtfq6t%d56g6#__en!v3$(t(1##(62'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


##############################################
            # local apps
    'home.apps.HomeConfig',
    'accounts.apps.AccountsConfig',
    'product.apps.ProductConfig',
    'orders.apps.OrdersConfig',

##############################################
            # third-party apps
    'storages',
    'django_celery_beat',
    'ckeditor',



]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'A.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'orders.context_processors.cart_context',
                'orders.context_processors.time',

            ],
        },
    },
]

WSGI_APPLICATION = 'A.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


SESSION_ENGINE='django.contrib.sessions.backends.cached_db'


CACHES={

    'default':{

        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION':'redis://127.0.0.1:6379',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
#media files

MEDIA_ROOT=BASE_DIR /'media'# addres whhere should we upload users media files
MEDIA_URL='/media/' #where are the stacked user files

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL='accounts.User'  # addding our user

STATICFILES_DIR=[BASE_DIR / 'static'] # files that will be added in every files


# Arvan cloud storage settings

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_S3_ACCESS_KEY_ID='e1b73ee2-5b7b-495e-b547-a470c2ca57a0'
AWS_S3_SECRET_ACCESS_KEY='179276af4bcbc6016912cf380dfba0e9df3e22ac06fee6179d07bd0227c9e50f'
AWS_S3_ENDPOINT_URL='https://s3.ir-thr-at1.arvanstorage.com'
AWS_STORAGE_BUCKET_NAME='django-05-13'
AWS_SERVICE_NAME='s3'
AWS_S3_FILE_OVERWRITE=False
AWS_LOCAL_STORAGE=f'{BASE_DIR}/aws/'




CKEDITOR_CONFIGS= {
        
        
            'awesome_ckeditor': {
                'toolbar':'full',
        }
    }
    








